apiVersion: v1
kind: Service
metadata: 
  name: shopping-backend
  labels:
    app: shopping-backend
spec:
  selector:
    app: shopping-backend
  ports:
    - name: http
      port: 80
      targetPort: 4000
  type: ClusterIP