apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-backend
  labels:
    app: shopping-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping-backend
  template:
    metadata:
      labels:
        app: shopping-backend
    spec:
      containers:
        - name: backend
          image: 124355676261.dkr.ecr.us-east-1.amazonaws.com/shopping-backend:latest
          ports:
            - containerPort: 4000
          readinessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"  