apiVersion: v1
kind: Service
metadata:
  name: shopping-frontend
  labels:
    app: shopping-frontend
spec:
  selector:
    app: shopping-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer
