apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-frontend
  labels:
    app: shopping-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping-frontend
  template:
    metadata:
      labels:
        app: shopping-frontend
    spec:
      containers:
        - name: frontend
          image: 124355676261.dkr.ecr.us-east-1.amazonaws.com/shopping-frontend:latest
          ports:
           - containerPort: 80
          readinessProbe:
            httpGet: 
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
